name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on: push

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"  # 指定具体版本以确保稳定性
    - name: Install pypa/build and dependencies
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Install project dependencies for SBOM generation
      run: pip install .  # 安装项目依赖以便SBOM工具能分析
    - name: Install SBOM generation tool
      run: pip install cyclonedx-bom
    - name: Generate SBOM from current environment
      run: cyclonedx-py environment --output sbom.json
    - name: Store the distribution packages and SBOM
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: |
          dist/
          sbom.json

  publish-to-pypi:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/flet-sherpa-onnx  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  create-release:
    name: Create Release with SBOM
    if: startsWith(github.ref, 'refs/tags/')
    needs: 
    - build
    - publish-to-pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create releases
      id-token: write
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: release-assets/
        
    - name: Create Release with SBOM
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release-assets/sbom.json
          release-assets/dist/*.whl
          release-assets/dist/*.tar.gz
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}